SQL_DATABASE = "airflowpoc"
SQL_HOST = "eu-west.connect.psdb.cloud"
SQL_PORT = "3306"
SQL_USER = "1pnu7p63kqbfr8e5agec"
SQL_PASSWORD = "pscale_pw_sFGH1EppM3vKqrGSb1Al0UBZOuDHTpxF9v9NW0tszcq"
ca_path = "ssl/ca-cert.pem"